// Generated by https://quicktype.io

namespace chatGptApi.ChatGpt
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using System.Text.Json.Serialization;

    public class ParametersModel
    {
        public ParametersModel(string prompt)
        {
            Prompt = $"Correct this english phrase: {prompt}";
            Temperature = 0;
            MaxTokens = 20;
            Model = "text-davinci-003";
            TopP = 1;
            N = 1;
            Stop = null;

        }

        [JsonPropertyName("model")]
        public string Model { get; set; }

        [JsonPropertyName("prompt")]
        public string Prompt { get; set; }

        [JsonPropertyName("max_tokens")]
        public long MaxTokens { get; set; }

        [JsonPropertyName("temperature")]
        public long Temperature { get; set; }

        [JsonPropertyName("top_p")]
        public long TopP { get; set; }

        [JsonPropertyName("n")]
        public long N { get; set; }

        [JsonPropertyName("stream")]
        public bool Stream { get; set; }

        [JsonPropertyName("logprobs")]
        public object Logprobs { get; set; }

        [JsonPropertyName("stop")]
        public string Stop { get; set; }
    }

}
